(define (make-rational num den)
  (cons num den))
(define (numerator rat)
  (car rat))
(define (denominator rat)
  (cdr rat))
(define (*rat a b)
  (make-rational (* (numerator a) (numerator b))
                 (* (denominator a) (denominator b))))
(define (print-rat rat)
  (word (numerator rat) '/ (denominator rat)))

(define (+rat a b)
  (make-rational (+ (* (/ (lcm (denominator a) (denominator b))
                          (denominator a))
                       (numerator a))
                    (* (/ (lcm (denominator a) (denominator b))
                          (denominator b))
                       (numerator b)))
                 (lcm (denominator a) (denominator b))))
